name: Publish to AUR

on:
  release:
    types: [published]

jobs:
  aur:
    uses: RXTX4816/cockpit-plugin-base-react/.github/workflows/release-plugin.yml@main
    with:
      plugin-name: cockpit-compose
      spec-file: cockpit-compose.spec
      aur-pkgname: cockpit-compose
      maintainer-name: RXTX4816
      maintainer-email: RXTX4816@proton.me
    secrets: inherit
