name: Semantic Release

on:
  workflow_dispatch:

permissions:
  contents: write

jobs:
  semantic-release:
    uses: RXTX4816/cockpit-plugin-base-react/.github/workflows/semantic-release-plugin.yml@main
    with:
      initial_version: v0.1.0
    secrets: inherit
